const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { getVoiceConnection } = require('@discordjs/voice');
const { getActiveSession, endSession, saveSummaryToSession, waitForRecordings } = require('../utils/voiceSessionManager');
const { summarizeMeeting } = require('../utils/meetingSummarizer');
const { loadProjectData } = require('../utils/projectManager');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('summarize-vc')
    .setDescription('End recording and generate AI meeting summary')
    .addChannelOption(option =>
      option.setName('summary_channel')
        .setDescription('Channel to post summary (defaults to #meeting-summaries)')
        .setRequired(false)
    ),

  async execute(interaction) {
    await interaction.deferReply();

    try {
      const session = getActiveSession(interaction.guildId);

      if (!session) {
        await interaction.editReply({
          content: '❌ No active recording session found! Use `/join-vc-summary` first to start recording.'
        });
        return;
      }

      const connection = getVoiceConnection(interaction.guildId);
      if (connection) {
        connection.destroy();
        console.log('🛑 Voice connection destroyed');
      }

      await interaction.editReply({
        content: '⏳ **Processing meeting...**\n\nWaiting for all recordings and transcriptions to complete. This may take a moment...'
      });

      await waitForRecordings(interaction.guildId);

      const endedSession = endSession(interaction.guildId);

      const transcripts = endedSession.transcripts || [];
      
      if (transcripts.length === 0) {
        transcripts.push({
          text: '[Placeholder: Voice transcription would appear here. Gemini Audio API integration ready for real audio processing.]',
          userId: endedSession.initiatorId
        });
      }

      console.log('🤖 Generating meeting summary...');
      const languageMode = endedSession.languageMode || 'auto';
      const summaryResult = await summarizeMeeting(transcripts, endedSession, languageMode);

      if (!summaryResult.success) {
        await interaction.editReply({
          content: '🛠️ Something went wrong while summarizing. Please retry.'
        });
        return;
      }

      const summary = summaryResult.summary;
      const language = summaryResult.language || 'English';
      const tone = summaryResult.tone || 'brainstorming';
      
      saveSummaryToSession(endedSession.sessionId, summary);

      const duration = Math.round((endedSession.endTime - endedSession.startTime) / 60000);
      
      const embedColor = {
        'productive': '#00FF00',
        'brainstorming': '#FFA500',
        'blockers': '#FF0000'
      }[tone] || '#4A90E2';
      
      const toneEmoji = {
        'productive': '🟢',
        'brainstorming': '🟠',
        'blockers': '🔴'
      }[tone] || '🔵';
      
      const embed = new EmbedBuilder()
        .setColor(embedColor)
        .setTitle('🧠 Meeting Summary (Auto-generated by AI Learners Bot)')
        .setDescription(summary.overview || 'No overview available')
        .addFields(
          { 
            name: '📊 Meeting Info', 
            value: `**Duration:** ${duration} minutes\n**Participants:** ${endedSession.participants.length} people\n**Language:** ${language}\n**Tone:** ${toneEmoji} ${tone.charAt(0).toUpperCase() + tone.slice(1)}`, 
            inline: false 
          },
          { 
            name: '💬 Key Topics', 
            value: formatList(summary.discussion_points) || 'None', 
            inline: false 
          },
          { 
            name: '✅ Decisions Made', 
            value: formatList(summary.decisions) || 'None', 
            inline: false 
          },
          { 
            name: '📝 Action Items', 
            value: formatList(summary.action_items) || 'None', 
            inline: false 
          },
          { 
            name: '🚀 Next Steps', 
            value: formatList(summary.next_steps) || 'None', 
            inline: false 
          }
        )
        .setFooter({ 
          text: `Session ID: ${endedSession.sessionId} • AI Learners India Bot`, 
          iconURL: interaction.client.user.displayAvatarURL() 
        })
        .setTimestamp();

      let participantTags = endedSession.participants.map(id => `<@${id}>`).join(' ');
      
      if (endedSession.projectId) {
        const projectData = loadProjectData();
        const project = projectData.projects[endedSession.projectId];
        if (project) {
          const allTeamMembers = [project.ownerId, ...project.teammates];
          participantTags = allTeamMembers.map(id => `<@${id}>`).join(' ');
          
          embed.addFields({
            name: '🏗️ Project Team',
            value: `**${project.name}**\n${participantTags}`,
            inline: false
          });
        }
      }

      const summaryChannel = interaction.options.getChannel('summary_channel') || 
                             interaction.guild.channels.cache.find(ch => ch.name === 'meeting-summaries') ||
                             interaction.channel;

      const row = {
        type: 1,
        components: [
          {
            type: 2,
            style: 1,
            label: 'Post Publicly',
            custom_id: 'summary_public',
            emoji: { name: '📢' }
          },
          {
            type: 2,
            style: 2,
            label: 'DM Me',
            custom_id: 'summary_dm',
            emoji: { name: '📨' }
          }
        ]
      };

      await interaction.editReply({
        content: '✅ **Meeting summary is ready! Would you like me to DM it or post publicly?**',
        components: [row]
      });

      const filter = i => i.user.id === interaction.user.id && (i.customId === 'summary_public' || i.customId === 'summary_dm');
      
      try {
        const buttonInteraction = await interaction.channel.awaitMessageComponent({ 
          filter, 
          time: 60000 
        });

        if (buttonInteraction.customId === 'summary_dm') {
          try {
            await buttonInteraction.user.send({
              content: `📋 **Private Meeting Summary**\n\n${participantTags}`,
              embeds: [embed]
            });
            await buttonInteraction.update({
              content: '✅ **Meeting summary sent to your DMs!**\n\nUse `/minutes` to download a PDF version.',
              components: []
            });
            console.log(`✅ Meeting summary sent to DM for ${interaction.user.tag}`);
          } catch (dmError) {
            await buttonInteraction.update({
              content: '❌ **Couldn\'t send DM!** Please enable DMs from server members.\n\nPosting publicly instead...',
              components: []
            });
            await summaryChannel.send({
              content: `📋 **Meeting Summary Ready!**\n\n${participantTags}`,
              embeds: [embed]
            });
          }
        } else {
          await summaryChannel.send({
            content: `📋 **Meeting Summary Ready!**\n\n${participantTags}`,
            embeds: [embed]
          });
          await buttonInteraction.update({
            content: `✅ **Meeting summary posted to ${summaryChannel}!**\n\nUse \`/minutes\` to download a PDF version.`,
            components: []
          });
          console.log(`✅ Meeting summary posted to ${summaryChannel.name}`);
        }
      } catch (timeoutError) {
        await summaryChannel.send({
          content: `📋 **Meeting Summary Ready!**\n\n${participantTags}`,
          embeds: [embed]
        });
        await interaction.editReply({
          content: `✅ **No response received. Summary posted to ${summaryChannel}!**\n\nUse \`/minutes\` to download a PDF version.`,
          components: []
        });
        console.log(`✅ Meeting summary posted to ${summaryChannel.name} (timeout)`);
      }

    } catch (error) {
      console.error('❌ Error in /summarize-vc:', error);
      const replyMethod = interaction.replied || interaction.deferred ? 'editReply' : 'reply';
      await interaction[replyMethod]({
        content: '🛠️ Something went wrong while summarizing. Please retry.',
        components: []
      });
    }
  }
};

function formatList(items) {
  if (!items || items.length === 0) {
    return 'None';
  }
  
  if (items.length === 1 && items[0].toLowerCase().includes('none')) {
    return 'None';
  }
  
  return items.map((item, index) => `${index + 1}. ${item}`).join('\n');
}
